### ISSUE TITLE
Consider a more powerful 'decode'

### ISSUE THREAD

**Issue by ekmett** [ekmett/ersatz#10]
We currently use

```haskell
decode :: Codec a => Solution -> a -> Maybe (Decoded a)
```

but we could upgrade it to

```haskell
decode :: (Alternative f, Codec a) => Solution -> a -> f (Decoded a)
```

Then we'd get the current definition from `f = Maybe`, but the `[]` instance could enumerate solutions, while other `Alternative` instances could might more intelligently.

**Comment by ekmett** [comment]
Done in HEAD.

**Comment by glguy** [comment]
I imagine we wouldn't be able to enumerate all solutions, but only those that explore possible choices for the unconstrained bits. There might be other solutions that are not compatible with the particular choices made by the prover

**Comment by ekmett** [comment]
Sure, it enumerates a subset of possible solutions, definitely.
