### ISSUE TITLE
bugfix -> needs new release on hackage

### ISSUE THREAD

**Issue by jwaldmann** [ekmett/ersatz#28]
I detected and fixed a serious error (that was introduced by me) in the SAT encoding of the `choose` function, see   https://github.com/ekmett/ersatz/pull/27 . This should be pushed to hackage soon-ish.

**Comment by RyanGlScott** [comment]
I've uploaded [`ersatz-0.4`](http://hackage.haskell.org/package/ersatz-0.4) to Hackage.
