### ISSUE TITLE
Get CI working with cryptominisat5

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/ersatz#40]
Now that the test suite requires the use of `cryptominisat5` in particular to work (after commit 2b70ac84906679bd8fc1f7adba6fef82f595dd35), the Travis build is failing ([example](https://travis-ci.org/ekmett/ersatz/jobs/535146708#L906)) due to `cryptominisat5` not being installed. Unfortunately, Ubuntu Xenial does not provide a `cryptominisat5` package, so Travis will have to build it itself, as far as I can tell.

Until this is resolved, I'm going to disable running the test suites on Travis so that we can get it back to green again.

**Comment by glguy** [comment]
I'm going to make a smart driver that runs whatever minisat it can find

**Comment by glguy** [comment]
Fixed in dfc150fd79b2a018ea7f603a838f97fcfd45eef9

**Comment by RyanGlScott** [comment]
Thanks, @glguy! I've uploaded [`ersatz-0.4.7`](http://hackage.haskell.org/package/ersatz-0.4.7) to Hackage with these changes so that we can resolve commercialhaskell/stackage#4571.
