### ISSUE TITLE
tests/Moore.hs : anyminisat => minisat (else, silent error when solvers are missing)

### ISSUE THREAD

**Issue by jwaldmann** [ekmett/ersatz#64]
I was trying to run tests/Moore.hs, and it just failed without any indication why.

The source code uses `solveWith anyminisat`, where
`anyminisat = trySolvers [cryptominisat5, cryptominisat, minisat]`

On my machine, I did not have `cryptominisat` installed, and that makes the call fail.

**Comment by glguy** [comment]
trySolvers was broken, it should fallback correctly now
