### ISSUE TITLE
improve Ersatz.Relation (docs, features) - or break out?

### ISSUE THREAD

**Issue by jwaldmann** [ekmett/ersatz#71]
I have a student working on Ersatz.Relation, and some doc fixes incoming (this week). 

There will also be additions (properties of relations that are used in abstract rewriting systems) - perhaps this is best done in a separate package (but it would be quite small).

Should Ersatz.Relation be broken out of ersatz as well? (It was not there to begin with.) This would reduce cognitive load for users and maintainers of  the core library - and reduce churn of version numbers! (by PVP, have to update on API changes)

**Comment by RyanGlScott** [comment]
I don't have a particularly strong feeling about whether `Ersatz.Relation` belongs in a separate library or not. I'm personally not too bothered by needing to bump the major version number for the `ersatz` library, as I don't think there are too many projects that depend on `ersatz` currently. That being said, if you think these upcoming additions to `Ersatz.Relation` would be useful outside of the context of `ersatz`'s core SAT solving functionality, perhaps that is a convincing argument in favor of splitting out `Relation`.

**Comment by RyanGlScott** [comment]
As far as Hackage releases go, I would be happy to make a new release whenever you want one. I could also give you Hackage upload permissions if that would make things easier.

**Comment by RyanGlScott** [comment]
I've uploaded [`ersatz-0.4.13`](https://hackage.haskell.org/package/ersatz-0.4.13) to Hackage.
