### ISSUE TITLE
ersatz-0.2.6.1 cannot compile its test suite

### ISSUE THREAD

**Issue by peti** [ekmett/ersatz#8]
Citing from http://hydra.cryp.to/build/578334/nixlog/1/raw:

    tests/properties.hs:32:19:
        Ambiguous occurrence ‘half_adder’
        It could refer to either ‘Main.half_adder’,
                                 defined at tests/properties.hs:36:1
                              or ‘Ersatz.half_adder’,
                                 imported from ‘Ersatz’ at tests/properties.hs:12:1-13
                                 (and originally defined in ‘Ersatz.Bits’)

    tests/properties.hs:33:19:
        Ambiguous occurrence ‘half_adder’
        It could refer to either ‘Main.half_adder’,
                                 defined at tests/properties.hs:36:1
                              or ‘Ersatz.half_adder’,
                                 imported from ‘Ersatz’ at tests/properties.hs:12:1-13
                                 (and originally defined in ‘Ersatz.Bits’)

**Comment by glguy** [comment]
This is already fixed in HEAD

**Comment by glguy** [comment]
the latest ersatz on hackage can build its test suite
